# This file was generated by GoReleaser. DO NOT EDIT.
cask "baobar" do
  version "0.1.1"

  on_macos do
    sha256 "f41632be852fcc72ab491d1859d1a07d9a5667d49c0dca78f4023320426f62ee"
    url "https://github.com/BrutalSystems/baobar/releases/download/v#{version}/baobar_#{version}_macOS.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "f399c8b225532a1ad9e248eb4eebf928b55b5cac5a69c6bd32738dd916c03608"
      url "https://github.com/BrutalSystems/baobar/releases/download/v#{version}/baobar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e11d01ffc4e3034c615c69ecf6e5bac9e4b61f981ca1ee2813922d84a6ed58c"
      url "https://github.com/BrutalSystems/baobar/releases/download/v#{version}/baobar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "baobar"
  desc "Menu bar indicator for OpenBao login state and token expiry"
  homepage "https://github.com/BrutalSystems/baobar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baobar"

  # No zap stanza required

  caveats <<~EOS
    Baobar needs your OpenBao address. Set it in
      ~/Library/Application Support/baobar/config.toml
    as `addr = "https://openbao.example.com"`, or export VAULT_ADDR.

    A config file is the durable option: "Start at login" runs Baobar from
    launchd, which does not inherit your shell environment.
  EOS
end
