# This file was generated by GoReleaser. DO NOT EDIT.
cask "baobar" do
  version "0.1.6"

  on_macos do
    sha256 "5f63ec362912b92e84ab6c2b34a0663b0fd54e44176aa17b0067dd2b432d4016"
    url "https://github.com/BrutalSystems/baobar/releases/download/v#{version}/baobar_#{version}_macOS.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "3d10cd850045ea2fb1e78d98ca869907434eee8f054cc987c5806190a5ac46d7"
      url "https://github.com/BrutalSystems/baobar/releases/download/v#{version}/baobar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d884d0b7db4d643f599c96413bd45adc57f0991724bd181df4cfd7c5e043f78"
      url "https://github.com/BrutalSystems/baobar/releases/download/v#{version}/baobar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "baobar"
  desc "Menu bar indicator for OpenBao login state and token expiry"
  homepage "https://github.com/BrutalSystems/baobar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baobar"

  # No zap stanza required

  caveats <<~EOS
    Just run Baobar — on first start it opens a browser tab asking for your
    OpenBao address, saves it, and carries on. There is no file to write.

    Expect that prompt even if VAULT_ADDR is set in your shell: "Start at
    login" runs Baobar from launchd, which does not inherit your shell
    environment. Answering once stores the address where launchd can see it.

    To change it later, or to prefill the login form with your username:
      ~/Library/Application Support/baobar/config.toml
      addr = "https://openbao.example.com"
      username = "you"
  EOS
end
