# This file was generated by GoReleaser. DO NOT EDIT.
cask "baobar" do
  version "0.1.2"

  on_macos do
    sha256 "c1692e53b8d9777cbe3a2c5a281ec78ebca6f7c5fcacab49e837b912568b4141"
    url "https://github.com/BrutalSystems/baobar/releases/download/v#{version}/baobar_#{version}_macOS.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "23d6fa37a4fef979ac394cf6d367ef56ff27b5d2575c716122be16df14ebb4da"
      url "https://github.com/BrutalSystems/baobar/releases/download/v#{version}/baobar_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d166811364e2a52f6a5d695994b60a56a5786787c991c0615d6cf3148616517"
      url "https://github.com/BrutalSystems/baobar/releases/download/v#{version}/baobar_#{version}_linux_arm64.tar.gz"
    end
  end

  name "baobar"
  desc "Menu bar indicator for OpenBao login state and token expiry"
  homepage "https://github.com/BrutalSystems/baobar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "baobar"

  # No zap stanza required

  caveats <<~EOS
    Baobar needs your OpenBao address. Set it in
      ~/Library/Application Support/baobar/config.toml
    as `addr = "https://openbao.example.com"`, or export VAULT_ADDR.

    A config file is the durable option: "Start at login" runs Baobar from
    launchd, which does not inherit your shell environment.
  EOS
end
